<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@820.vd1a_6cc65ef33">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@2725.v7b_c717eb_12ce">
    <parentIds>
      <string>69</string>
    </parentIds>
    <id>70</id>
    <startId>62</startId>
  </node>
  <actions>
    <wf.a.TimingAction plugin="workflow-api@1165.v02c3db_a_6b_e36">
      <startTime>1657015892945</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@1165.v02c3db_a_6b_e36">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 1</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:664)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:610)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:554)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(Unknown Source)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)</trace>
          <trace>java.base/java.lang.Thread.run(Unknown Source)</trace>
        </stackTrace>
        <suppressedExceptions class="empty-list"/>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>